export const tools = [
  { name: 'React', logo: '/tech/react.svg' },
  { name: 'Next.js', logo: '/tech/nextjs.svg' },
  { name: 'TypeScript', logo: '/tech/typescript.svg' },
  { name: 'JavaScript', logo: '/tech/javascript.svg' },
  { name: 'Node.js', logo: '/tech/nodedotjs.svg' },
  { name: 'Python', logo: '/tech/python.svg' },
  { name: 'PHP', logo: '/tech/php.svg' },
  { name: 'Laravel', logo: '/tech/laravel.svg' },
  { name: 'Tailwind CSS', logo: '/tech/tailwindcss.svg' },
  { name: 'MongoDB', logo: '/tech/mongodb.svg' },
  { name: 'Supabase', logo: '/tech/supabase.svg' },
  { name: 'AWS', logo: '/tech/aws.svg' },
  { name: 'Vercel', logo: '/tech/vercel.svg' },
  { name: 'Cloudflare', logo: '/tech/cloudflare.svg' },
  { name: 'Docker', logo: '/tech/docker.svg' },
  { name: 'GitHub', logo: '/tech/github.svg' },
  { name: 'Cursor', logo: '/tech/cursor.svg' },
  { name: 'n8n', logo: '/tech/n8n.svg' },
  { name: 'Make', logo: '/tech/make.svg' },
  { name: 'Zapier', logo: '/tech/zapier.svg' },
  { name: 'OpenAI', logo: '/tech/openai.svg' },
  { name: 'Vapi', logo: '/tech/vapi.svg' },
  { name: 'GoHighLevel', logo: '/tech/gohighlevel.svg' },
  { name: 'HubSpot', logo: '/tech/hubspot.svg' },
  { name: 'Follow Up Boss', logo: '/tech/followupboss.svg' },
  { name: 'Twilio', logo: '/tech/twilio.svg' },
  { name: 'Mailgun', logo: '/tech/mailgun.svg' },
  { name: 'Calendly', logo: '/tech/calendly.svg' },
  { name: 'Stripe', logo: '/tech/stripe.svg' },
  { name: 'WordPress', logo: '/tech/wordpress.svg' },
  { name: 'Shopify', logo: '/tech/shopify.svg' },
  { name: 'Airtable', logo: '/tech/airtable.svg' },
  { name: 'Asana', logo: '/tech/asana.svg' },
  { name: 'DocuSign', logo: '/tech/docusign.svg' },
  { name: 'Canva', logo: '/tech/canva.svg' },
  { name: 'YouTube', logo: '/tech/youtube.svg' },
]

export const stackGroups = [
  {
    title: 'Product and frontend',
    items: ['React', 'Next.js', 'TypeScript', 'JavaScript', 'Tailwind CSS', 'Cursor'],
  },
  {
    title: 'Backend and data',
    items: ['Node.js', 'PHP', 'Laravel', 'Python', 'MongoDB', 'Supabase'],
  },
  {
    title: 'Cloud and DevOps',
    items: ['AWS', 'Vercel', 'GitHub', 'Cloudflare', 'Docker'],
  },
  {
    title: 'CRM and sales ops',
    items: ['GoHighLevel', 'HubSpot', 'Follow Up Boss', 'Calendly', 'Stripe'],
  },
  {
    title: 'Automation and AI',
    items: ['n8n', 'Make', 'Zapier', 'OpenAI', 'Vapi', 'Twilio', 'Mailgun'],
  },
  {
    title: 'Content and delivery',
    items: ['WordPress', 'Shopify', 'Airtable', 'Asana', 'DocuSign', 'Canva', 'YouTube'],
  },
]
